# Generated by Django 4.2.2 on 2023-06-20 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=120, verbose_name='Email')),
                ('subject', models.TextField(max_length=120, verbose_name='Сообщение')),
                ('message', models.TextField(max_length=400, verbose_name='Cooбщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events/', verbose_name='Image')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.ImageField(upload_to='events/', verbose_name='Name')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('phone', models.CharField(max_length=13, verbose_name='phone')),
                ('date', models.DateField(verbose_name='date')),
                ('time', models.TimeField(verbose_name='time')),
                ('persons', models.PositiveIntegerField(verbose_name='persons')),
                ('message', models.TextField(max_length=500, verbose_name='message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Изображение')),
                ('first_name', models.CharField(max_length=120, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=120, verbose_name='Фамилия')),
                ('description', models.TextField(max_length=120, verbose_name='Тематика')),
                ('profession', models.CharField(max_length=120, verbose_name='Профессия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Menu')),
                ('image', models.ImageField(upload_to='food/', verbose_name='Image')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menu',
            },
        ),
        migrations.CreateModel(
            name='Chefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='shefs/', verbose_name='Изображение')),
                ('full_name', models.CharField(max_length=120, verbose_name='ФИО')),
                ('twitter', models.URLField(blank=True, max_length=300, null=True, unique=True, verbose_name='twitter Url')),
                ('facebook', models.URLField(blank=True, max_length=300, null=True, unique=True, verbose_name='facebook Url')),
                ('instagram', models.URLField(blank=True, max_length=300, null=True, unique=True, verbose_name='instagram Url')),
                ('linkedin', models.URLField(blank=True, max_length=300, null=True, unique=True, verbose_name='linkedin Url')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food.role', verbose_name='Роль повара')),
            ],
            options={
                'verbose_name': 'Повар',
                'verbose_name_plural': 'Повара',
            },
        ),
    ]
